### ISSUE TITLE
Doesn't render?

### ISSUE THREAD

**Issue by macMikey** [trevordevore/levurehelper-file_browser#2]
Still debugging, but does not render.  I got the group to install, and the behaviors all seem to be current.  Firing the (corrected) example code (see PR #1) seems to generate the array, but the rendering never happens.

**Comment by macMikey** [comment]
Somehow in this installed project, dataView is not passed ``renderView```.  When I look at the projectBrowser, everything looks ok, and I can open the three behavior scripts, but when DVT passes ```renderView```, DV doesn't get the message.

**Comment by macMikey** [comment]
Ugh.  If I create a new project from scratch it works, even with the app.yml file from the project that doesn't work.

**Comment by trevordevore** [comment]
If you are adding this to an existing project then make sure you update Levure to 0.9.12. It adds support for dependencies. The DataView helper needs to be loaded first, then the DataView Tree, and finally the File Browser. Dependencies allow this.

**Comment by macMikey** [comment]
When I updated I ran into the problem with the infinite loop when the framework tries to handle dependencies (see the issue in levure itself).

**Comment by trevordevore** [comment]
I just fixed that in develop. But making sure you have all of the helpers present will fix the issue as well.

**Comment by macMikey** [comment]
See new error message.  It sure looks like all the helpers are present.  See screenshot
<img width="533" alt="screen shot 2019-01-20 at 00 40 14" src="https://user-images.githubusercontent.com/10867016/51435707-06e0d180-1c4c-11e9-9948-85e5ec65a4ea.png">

and the app.yml:
<img width="558" alt="screen shot 2019-01-20 at 00 40 32" src="https://user-images.githubusercontent.com/10867016/51435710-119b6680-1c4c-11e9-824e-cc002f7bc030.png">

**Comment by macMikey** [comment]
OK, with latest helpers and latest levure, all is good.
